pub mod accounting;
pub mod analytics;
pub mod cohort;
pub mod context;
pub mod coverage;
pub mod envio;
pub mod error;
pub mod events;
pub mod evidence;
pub mod funding;
pub mod funding_checkpoint;
pub mod identity;
pub mod ledger;
pub mod live;
pub mod market_inputs;
pub mod metrics;
pub mod money;
pub mod pipeline;
pub mod publication;
pub mod quality;
pub mod registry;
pub mod serve;
pub mod signals;
pub mod store;

pub use coverage::CoverageEvidence;
pub use error::{DataQualityError, Result};
pub use events::{load_fixture, CanonicalEvent, Fixture, LifecycleKind};
pub use identity::{AsOf, EventId, PositionId};
pub use ledger::{replay, Ledger};
pub use pipeline::{run_fixture, Pulse};
pub use registry::{load_registry, ProtocolRegistry};
